// generates CSS classes for Heroicons used in the app
// scans .razor and .html files for icon-[heroicons--*] classes and outputs icons.css

import { readFileSync, writeFileSync, readdirSync, statSync } from 'fs';
import { join } from 'path';
import { getIconData, iconToSVG, iconToHTML } from '@iconify/utils';

// load the heroicons icon set
const iconsData = JSON.parse(
    readFileSync(new URL('../node_modules/@iconify-json/heroicons/icons.json', import.meta.url), 'utf8')
);

// recursively find all .razor and .html files
function findFiles(dir, extensions) {
    let results = [];
    for (const entry of readdirSync(dir)) {
        const fullPath = join(dir, entry);
        const stat = statSync(fullPath);
        if (stat.isDirectory() && !entry.startsWith('.') && entry !== 'node_modules' && entry !== 'bin' && entry !== 'obj') {
            results = results.concat(findFiles(fullPath, extensions));
        } else if (extensions.some(ext => entry.endsWith(ext))) {
            results.push(fullPath);
        }
    }
    return results;
}

// scan source files for icon class usage: icon-[heroicons--name]
const sourceDir = join(import.meta.dirname, '..');
const files = findFiles(sourceDir, ['.razor', '.html', '.cs']);
const iconPattern = /icon-\[heroicons--([a-z0-9-]+)\]/g;
const usedIcons = new Set();

for (const file of files) {
    const content = readFileSync(file, 'utf8');
    let match;
    while ((match = iconPattern.exec(content)) !== null) {
        usedIcons.add(match[1]);
    }
}

if (usedIcons.size === 0) {
    console.log('No icon classes found in source files. Writing empty icons.css.');
    writeFileSync(join(sourceDir, 'wwwroot', 'css', 'icons.css'), '/* no icons used */\n');
    process.exit(0);
}

console.log(`Found ${usedIcons.size} icon(s): ${[...usedIcons].join(', ')}`);

// generate CSS for each icon
let css = '/* auto-generated by build-icons.mjs — do not edit */\n\n';

for (const name of [...usedIcons].sort()) {
    const iconData = getIconData(iconsData, name);
    if (!iconData) {
        console.warn(`  Warning: heroicons--${name} not found, skipping`);
        continue;
    }

    const rendered = iconToSVG(iconData);
    const svgAttrs = Object.entries(rendered.attributes)
        .map(([k, v]) => `${k}="${v}"`)
        .join(' ');
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" ${svgAttrs}>${rendered.body}</svg>`;
    const encoded = `url("data:image/svg+xml,${encodeURIComponent(svg)}")`;

    css += `.icon-\\[heroicons--${name}\\] {\n`;
    css += `    display: inline-block;\n`;
    css += `    width: 1em;\n`;
    css += `    height: 1em;\n`;
    css += `    background-color: currentColor;\n`;
    css += `    -webkit-mask-image: ${encoded};\n`;
    css += `    mask-image: ${encoded};\n`;
    css += `    -webkit-mask-repeat: no-repeat;\n`;
    css += `    mask-repeat: no-repeat;\n`;
    css += `    -webkit-mask-size: 100% 100%;\n`;
    css += `    mask-size: 100% 100%;\n`;
    css += `}\n\n`;
}

writeFileSync(join(sourceDir, 'wwwroot', 'css', 'icons.css'), css);
console.log(`Generated wwwroot/css/icons.css`);
